### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by RubenJ01** [jforstneric/5e_encounter_generator#1]
Hey!

Im interested in creating an encounter generator for my discord bot, and I was wondering if I could use your concept for this. Any way I can contact you about this? My discord is RubenJ01#2001

Thanks in advance!

**Comment by jforstneric** [comment]
Hey,

Of course, I forgot to add a license, will do, but consider it licensed under an MIT license so feel free to use it any way you want :-)

If you have any questions or anything, let me know, I can add you on Discord if there's anything specific I can answer regarding the code. I also have a private version which is essentially identical but has the functions split up into separate files, if you're interested in that as well.

**Comment by RubenJ01** [comment]
If you could contact me trough discord that would be amazing! Thanks for the quick response

**Comment by RubenJ01** [comment]
Its either ruben#2001 or rubenj01#2001 could be either

**Comment by jforstneric** [comment]
Added the first one (ruben#2001). Warning that I'm not very active on Discord but I'll check it a bit more often.

**Comment by RubenJ01** [comment]
Im not getting a friend request, its Ruben#2001 so capital R, whats your discord name and tag?
